/**
 * Background sync coordinator.
 *
 * Capacitor doesn't ship a first-party background-task API for Android.
 * The production plan is:
 *   1. Foreground: `App` lifecycle events → run `syncNow()` on resume.
 *   2. Real background: implement a small Kotlin `WorkManager` job in
 *      `android/app/src/main/java/app/vairagya/sync/SyncWorker.kt`
 *      that opens the app in headless mode and calls into JS via a
 *      custom Capacitor plugin (`VairagyaSync`) — see
 *      `android/app/src/main/java/app/vairagya/sync/README.md`
 *      generated by ANDROID-BUILD.md.
 *
 * This module exposes the JS-side contract now so app code can call
 * `syncNow()` from anywhere and the native side can be plugged in later
 * without touching React components.
 */
import { App } from "@capacitor/app";
import { isNative } from "./platform";

type SyncFn = () => Promise<void>;
let registered: SyncFn | null = null;
let listenerAttached = false;

export function registerSyncHandler(fn: SyncFn): void {
  registered = fn;
  if (!listenerAttached && isNative()) {
    listenerAttached = true;
    void App.addListener("appStateChange", (state) => {
      if (state.isActive) void syncNow();
    });
    void App.addListener("resume", () => {
      void syncNow();
    });
  }
}

export async function syncNow(): Promise<void> {
  if (!registered) return;
  try {
    await registered();
  } catch (err) {
    console.warn("[background-sync] handler failed", err);
  }
}
