#!/usr/bin/env python3
"""Idempotently inject Vairagya's required <uses-permission> entries into the
Android manifest generated by `cap add android`, and register the SMS handler
intent filter so Android 11+ can resolve the SMS provider.

Runs from CI after `bunx cap sync android`. Safe to run multiple times.
"""
from pathlib import Path
import re
import sys

MANIFEST = Path("android/app/src/main/AndroidManifest.xml")

REQUIRED_PERMISSIONS = [
    "android.permission.INTERNET",
    "android.permission.READ_SMS",
    "android.permission.RECEIVE_SMS",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.USE_BIOMETRIC",
    "android.permission.USE_FINGERPRINT",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    "android.permission.FOREGROUND_SERVICE",
    "android.permission.WAKE_LOCK",
    "android.permission.VIBRATE",
]

# <queries> element lets Android 11+ package-visibility rules allow the
# capacitor-sms-inbox plugin to see the default SMS app when scanning.
QUERIES_BLOCK = """    <queries>
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data android:scheme="smsto" />
        </intent>
        <intent>
            <action android:name="android.provider.Telephony.SMS_RECEIVED" />
        </intent>
    </queries>
"""


def main() -> int:
    if not MANIFEST.exists():
        print(f"[patch-manifest] {MANIFEST} not found; skipping.")
        return 0

    xml = MANIFEST.read_text()

    # Inject any missing <uses-permission> lines right before <application>.
    lines_to_add: list[str] = []
    for perm in REQUIRED_PERMISSIONS:
        if f'android:name="{perm}"' not in xml:
            lines_to_add.append(
                f'    <uses-permission android:name="{perm}" />'
            )

    if lines_to_add:
        block = "\n".join(lines_to_add) + "\n"
        xml = re.sub(
            r"(\s*)(<application\b)",
            lambda m: "\n" + block + m.group(1) + m.group(2),
            xml,
            count=1,
        )

    # Inject <queries> block once.
    if "<queries>" not in xml:
        xml = re.sub(
            r"(\s*)(<application\b)",
            lambda m: "\n" + QUERIES_BLOCK + m.group(1) + m.group(2),
            xml,
            count=1,
        )

    MANIFEST.write_text(xml)
    print(f"[patch-manifest] Updated {MANIFEST}")
    print(xml)
    return 0


if __name__ == "__main__":
    sys.exit(main())
